channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - bokeh>=3.3.0
  - cachey=0.2.1
  - cytoolz>=0.12
  - dask=2024.4.1
  - distributed=2024.4.1
  - h5py=3.11.0
  - jq=1.6
  - jupyter-server-proxy
  - lz4>=4.3.2
  - msgpack-python=1.0.7
  - nomkl
  - numpy>=1.26.0
  - pandas=2.2.2
  - psutil>=5.7.2
  - python-blosc=1.10.6
  - s3fs>=2021.9.0
  - scipy>=1.12.0
  - streamz=0.6.3
  - tblib>=1.6.0
  - tornado=6.4
  - zarr=2.16.1
  - pip:
    - cloudpickle==3.0.0
