channels:
  - conda-forge
dependencies:
  - python=3.12
  - dask=2025.5.1
  - distributed=2025.5.1
  - pip
  - flatten_json
  - numpy>=1.26,<2
  - pyyaml
  - zarr=2.18.7
  - pip:
    - pynrrd==1.1.3
    - ome-zarr-models==0.1.6
    - git+https://github.com/GFleishman/fishspot.git@84f5b8187b
    - git+https://github.com/GFleishman/ClusterWrap.git@fa718ac49
    - simpleitk==2.5.2
