channels:
  - conda-forge
  - pytorch
dependencies:
  - pip
  - flatten_json
  - imagecodecs
  - numpy>=1.26.0
  - pyyaml
  - scikit-image>=0.21.0
  - scikit-learn>=1.4.1
  - zarr=2.13.3
  - pytorch=2.1.2
  - roifile
  - pip:
    - cellpose==3.1.0
    - cellpose[distributed]==3.1.0
    - pynrrd
    - tornado
    - torchvision
