channels:
  - conda-forge
dependencies:
  - pip
  - flatten_json
  - imagecodecs
  - numpy=2.2.0
  - pyyaml
  - scikit-image>=0.21.0
  - scikit-learn>=1.4.1
  - zarr=2.16.1
  - pydantic=2.7.1
  - roifile
  - pip:
    - cellpose==3.1.0
    - cellpose[distributed]==3.1.0
    - pynrrd
    - torch==2.6.0
    - tornado
    - torchvision
