channels:
  - conda-forge
dependencies:
  - python=3.12
  - dask=2025.1.0
  - distributed=2025.1.0
  - pip
  - flatten_json
  - imagecodecs
  - numpy>=1.26.0,<2
  - pyyaml
  - scikit-image>=0.21.0
  - scikit-learn>=1.4.1
  - zarr=2.16.1
  - pydantic=2.7.1
  - roifile
  - pip:
    - cellpose==3.1.0
    - cellpose[distributed]==3.1.0
    - pynrrd
    - tornado
    - torch==2.6.0
    - torchvision
