channels:
  - conda-forge
dependencies:
  - python=3.12
  - dask=2025.5.1
  - distributed=2025.5.1
  - dask-image=2024.5.3
  - pip
  - flatten_json
  - imagecodecs
  - numpy>=1.26.0,<2
  - pydantic=2.7.1
  - pyyaml
  - scikit-image>=0.21.0
  - scikit-learn>=1.4.1
  - zarr=2.18.7
  - pip:
    - ome-zarr-models==0.1.6
    - tornado
    - xarray-multiscale==2.1.0
